DROP TABLE IF EXISTS tblRabobankMaster;
CREATE TABLE tblRabobankMaster (id INTEGER PRIMARY KEY AUTOINCREMENT,
selfAccount VARCHAR(50) NOT NULL,
currency VARCHAR(10) NOT NULL,
processDate DATE NOT NULL,
debcred VARCHAR(10) NOT NULL,
amount REAL NOT NULL,
crossAccount VARCHAR(50) NOT NULL,
crossAccountHolder VARCHAR (100),
interestDate DATE,
typ VARCHAR(10),
unknown1 VARCHAR(200),
description1 VARCHAR(200),
description2 VARCHAR(200),
description3 VARCHAR(200),
description4 VARCHAR(200),
unknown2 VARCHAR(200),
unknown3 VARCHAR(200),
transactionReference VARCHAR(200),
incassantId VARCHAR(50),
kenmerkMachtiging VARCHAR (50));

